import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'


const myFont = localFont({
  weight: '800',
  variable: '--font-ProximaNova-Bold',
  src: '../../public/fonts/ProximaNova-Bold.ttf'
 })


 const myFont2 = localFont({
  weight: '400',
  variable: '--font-ProximaNova-Regular',
   src: '../../public/fonts/ProximaNova-Regular.ttf'
 })
 
// const myFont2 = localFont({ src: '../../public/font/ProximaNova-Regular.ttf' })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable} ${myFont2.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
